import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#fdddb9',
        'surface-container-highest': '#e4e2df',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'surface-dim': '#dbdad7',
        'outline': '#80756d',
        'on-surface-variant': '#4e453e',
        'error-container': '#ffdad6',
        'tertiary': '#674e34',
        'on-secondary': '#ffffff',
        'tertiary-container': '#81664a',
        'on-background': '#1b1c1a',
        'outline-variant': '#d1c4ba',
        'on-secondary-container': '#786044',
        'surface-container-low': '#f5f3f0',
        'primary': '#535353',
        'on-error-container': '#93000a',
        'inverse-surface': '#30312f',
        'on-secondary-fixed': '#281803',
        'surface-container-high': '#eae8e5',
        'primary-fixed': '#e4e2e1',
        'on-surface': '#1b1c1a',
        'on-secondary-fixed-variant': '#584329',
        'background': '#fbf9f6',
        'on-tertiary-container': '#ffe9d6',
        'error': '#ba1a1a',
        'on-primary': '#ffffff',
        'surface-bright': '#fbf9f6',
        'inverse-on-surface': '#f2f0ed',
        'surface-container': '#efeeeb',
        'on-primary-container': '#efecec',
        'surface': '#fbf9f6',
        'primary-fixed-dim': '#c8c6c6',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e4e2df',
        'secondary': '#715a3e',
        'primary-container': '#6c6b6b',
        'secondary-fixed': '#fdddb9',
        'secondary-fixed-dim': '#e0c29f',
        'tertiary-fixed': '#ffddbb',
        'tertiary-fixed-dim': '#e3c19f',
        'surface-tint': '#5f5e5e',
        'on-primary-fixed': '#1b1c1c',
        'on-primary-fixed-variant': '#474747',
        'inverse-primary': '#c8c6c6',
        'on-tertiary-fixed': '#291803',
        'on-tertiary-fixed-variant': '#5a4229',
        'on-secondary-container-alt': '#786044',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.7s ease-out forwards',
        'fade-in': 'fadeIn 0.6s ease-out forwards',
      },
    },
  },
  plugins: [],
}
export default config
